# Generated by Django 3.0.2 on 2020-01-26 12:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200125_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealHistoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.csv_file_path)),
            ],
        ),
    ]
